POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5hc2htIiwiaWQiOiI2OWI0MGE5OGNkZDU5ZWRiYTcxZDlhZjciLCJpYXQiOjE3NzM2NTYxMzZ9.DxiVgBU06OmN74wNBrnINrkf8ripKRS0kKeLeYWUANc

{
    "title": "Rise of Kenyan Startups",
    "author": "Njegah",
    "url": "https://www.startupkenya.com/rise-of-kenyan-startups",
    "likes": 45
}